### ISSUE TITLE
ansible_facts' is undefined

### ISSUE THREAD

**Issue by memoryleak** [samdoran/ansible-role-yum-cron#1]
Steps to reproduce:

- clone repository
- within the folder, install ansible 2.4:
`virtualenv .venv && source .venv/bin/activate && pip install ansible==2.4.* molecule[docker] docker`
 - molecule test

When executing the role (using moleucle test) with Ansible 2.4.* following exception is thrown:

`fatal: [yum_cron-test]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_facts' is undefined\n\nThe error appears to have been in '/Users/haydar.ciftci/Temp/yum_cron/molecule/default/playbook.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug:\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'ansible_facts' is undefined"}`

It's not being thrown with ansible 2.7. However, the meta.yml requires minimum 2.4.

**Comment by samdoran** [comment]
I should update the `meta/main.yml` since the `ansible_facts` dict was added in 2.5.

**Comment by samdoran** [comment]
Fixed by increasing minimum Ansible version in c31b82a67c1efd1963a8fc44288bcbfb5399c72c
