### ISSUE TITLE
Broken installation

### ISSUE THREAD

**Issue by diaspar** [samdoran/ansible-role-yum-cron#2]
HI!

I just tried to download this package using ansible-galaxy and this is what I got:

```
$ ansible-galaxy install samdoran.yum_cron
Starting galaxy role install process
- downloading role 'yum_cron', owned by samdoran
- downloading role from https://github.com/samdoran/ansible-role-yum-cron/archive/master.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
[WARNING]: - samdoran.yum_cron was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
It seems there's no master.tar.gz in the github repository or some path has changed. This may be related to the whole main vs master change Github applied because this works:

https://github.com/samdoran/ansible-role-yum-cron/archive/main.tar.gz

**Comment by samdoran** [comment]
I reimported my roles in Ansible Galaxy and they now target the new default branch. Thanks for letting me know.
